#!/usr/bin/env node
'use strict';
/**
 * ============================================================================
 *  Dino Royale Evolution - CLIENT BUILDER
 * ============================================================================
 *  The playable client is a single self-contained `index.html`. This tool
 *  regenerates the block of shared modules that the client and the server must
 *  agree on byte-for-byte:
 *
 *      server/lib/worldgen.js   deterministic world generation
 *      server/lib/protocol.js   wire format + tuning constants
 *      server/lib/content.js    weapons, items, saurians, progression
 *      server/lib/movement.js   character physics (prediction + authority)
 *
 *  Those four files are inlined into index.html between the SHARED markers.
 *  Everything else in index.html is hand-authored and left untouched.
 *
 *  Usage:
 *      node tools/build-client.js          # rewrite the shared block
 *      node tools/build-client.js --check  # verify it is up to date (CI)
 * ============================================================================
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const INDEX = path.join(ROOT, 'index.html');
const SHARED_FILES = ['worldgen.js', 'protocol.js', 'content.js', 'movement.js'];

const BEGIN = '<script id="shared-modules" type="text/plain">';
const END = '</' + 'script><!-- /shared-modules -->';

function buildSharedSource() {
  const parts = [];
  parts.push('/* ==========================================================================');
  parts.push('   SHARED MODULES - generated by tools/build-client.js, do not edit here.');
  parts.push('   Byte-identical copies of server/lib/{worldgen,protocol,content,movement}.js');
  parts.push('   so the client and the authoritative server agree on every value.');
  parts.push('   ========================================================================== */');
  for (const file of SHARED_FILES) {
    const src = fs.readFileSync(path.join(ROOT, 'server', 'lib', file), 'utf8');
    if (src.includes('</scr' + 'ipt')) {
      throw new Error(`${file} contains a closing script tag and cannot be inlined.`);
    }
    parts.push(`\n/* ---------- server/lib/${file} ---------- */`);
    parts.push(src.replace(/^'use strict';\n/, ''));
  }
  return parts.join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const html = fs.readFileSync(INDEX, 'utf8');
  const start = html.indexOf(BEGIN);
  const end = html.indexOf(END, start);
  if (start < 0 || end < 0) {
    console.error('[build] shared-modules markers not found in index.html');
    process.exit(1);
  }

  const shared = buildSharedSource();
  const next = html.slice(0, start + BEGIN.length) + '\n' + shared + '\n' + html.slice(end);

  if (check) {
    if (next !== html) {
      console.error('[build] index.html is out of date - run: node tools/build-client.js');
      process.exit(1);
    }
    console.log('[build] shared modules in index.html are up to date');
    return;
  }

  if (next === html) {
    console.log('[build] index.html already up to date');
  } else {
    fs.writeFileSync(INDEX, next, 'utf8');
    console.log(`[build] refreshed shared modules in index.html (${(shared.length / 1024).toFixed(1)} KiB)`);
  }
}

main();
